export const LOADING_USER = "LOADING_USER"
export const LOADING_DATA = "LOADING_DATA"
export const SET_REQUESTED = "SET_REQUESTED"

export const SET_PRODUCTS = "SET_PRODUCTS"
export const SET_NOTIFICATION = "SET_NOTIFICATION"

export const SET_CART_ITEMS = "SET_CART_ITEMS"
export const ADD_CART_ITEM = "ADD_CART_ITEM"
export const DELETE_CART_ITEM = "DELETE_CART_ITEM"

export const SET_AUTHENTICATED = "SET_AUTHENTICATED"
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED"
